### ISSUE TITLE
User/Role List could not be obtained: after installation

### ISSUE THREAD

**Issue by chemajf** [pentaho/pentaho-platform#4295]
Hi,

I'm just installing Pentaho Server 8.1 (Archive Installation) CE in a virtual machine Ubuntu 16.04.2 LTS, Java 8 and MySQL 5.7
I have been using the manual of Home - Pentaho Documentation [https://help.pentaho.com/Documentation/8.1/Setup/Installation/Archive](url) and when start Pentaho Server (/home/pentaho/pentaho/server/pentaho-server/start-pentaho.sh) it gives me several errors:

`11:12:04,843 ERROR [CompositeUserRoleListService] User/Role List could not be obtained.
java.lang.IllegalStateException: Target of Bean was never resolved: org.springframework.security.core.userdetails.UserDetailsService
        at org.pentaho.platform.engine.core.system.objfac.spring.BeanBuilder$1.invoke(BeanBuilder.java:159)
        at com.sun.proxy.$Proxy84.loadUserByUsername(Unknown Source)
        at org.pentaho.platform.plugin.services.security.userrole.ChainedUserDetailsService.loadUserByUsername(ChainedUserDetailsService.java:50)
        at org.pentaho.platform.plugin.services.security.userrole.PentahoCachingUserDetailsService.loadUserByUsername(PentahoCachingUserDetailsService.java:77)
        at org.pentaho.platform.security.userroledao.service.UserRoleDaoUserRoleListService.getRolesForUser(UserRoleDaoUserRoleListService.java:146)
        at org.pentaho.platform.plugin.services.security.userrole.ExtraRolesUserRoleListServiceDecorator.getRolesForUser(ExtraRolesUserRoleListServiceDecorator.java:116)
        at org.pentaho.platform.plugin.services.security.userrole.CompositeUserRoleListService$7.perform(CompositeUserRoleListService.java:125)
        at org.pentaho.platform.plugin.services.security.userrole.CompositeUserRoleListService.collectResultsForOperation(CompositeUserRoleListService.java:134)
        at org.pentaho.platform.plugin.services.security.userrole.CompositeUserRoleListService.getRolesForUser(CompositeUserRoleListService.java:123)
        at org.pentaho.platform.engine.security.SecurityHelper.createAuthentication(SecurityHelper.java:354)
        at org.pentaho.platform.engine.security.SecurityHelper.runAsSystem(SecurityHelper.java:417)
        at pt.webdetails.cpf.repository.pentaho.unified.PluginRepositoryResourceAccess.getSystemAccessRepository(PluginRepositoryResourceAccess.java:48)
        at pt.webdetails.cpf.repository.pentaho.unified.PluginRepositoryResourceAccess.getRepository(PluginRepositoryResourceAccess.java:65)
        at pt.webdetails.cpf.repository.pentaho.unified.UnifiedRepositoryAccess.getRepositoryFile(UnifiedRepositoryAccess.java:132)
        at pt.webdetails.cpf.repository.pentaho.unified.UnifiedRepositoryAccess.fileExists(UnifiedRepositoryAccess.java:62)
        at pt.webdetails.cdf.dd.extapi.FileHandler.createBasicDirIfNotExists(FileHandler.java:144)
        at pt.webdetails.cdf.dd.CdeEngine.ensureDirExists(CdeEngine.java:121)
        at pt.webdetails.cdf.dd.CdeEngine.ensureBasicDirs(CdeEngine.java:66)
        at pt.webdetails.cdf.dd.CdeLifeCycleListener.ready(CdeLifeCycleListener.java:39)
        at org.pentaho.platform.web.http.context.PentahoSystemReadyListener.contextInitialized(PentahoSystemReadyListener.java:56)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1141)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`
I've gone over and over again the configuration of MySQL, jackrabbit, quartz and hibernate and everything is correct. I can enter each of the schemes (jackrabbit, quartz and hibernate) created with the created users.

In http://localhost:8080/pentaho/Login I try to login, but it gives me this error:
`12:12:05,315 ERROR [UsernamePasswordAuthenticationFilter] An internal error occurred while trying to authenticate the user.
org.springframework.security.authentication.InternalAuthenticationServiceException: Target of Bean was never resolved: org.springframework.security.core.userdetails.UserDetailsService
        at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:126)
        at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:144)
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174)
        at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:94)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:121)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.pentaho.platform.web.http.security.HttpSessionReuseDetectionFilter.doFilter(HttpSessionReuseDetectionFilter.java:136)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.pentaho.platform.web.http.filters.HttpSessionPentahoSessionIntegrationFilter.doFilter(HttpSessionPentahoSessionIntegrationFilter.java:276)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.pentaho.platform.web.http.filters.SystemStatusFilter.doFilter(SystemStatusFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.pentaho.platform.web.http.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.pentaho.platform.web.http.filters.WebappRootForwardingFilter.doFilter(WebappRootForwardingFilter.java:73)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.pentaho.platform.web.http.filters.PentahoPathDecodingFilter.doFilter(PentahoPathDecodingFilter.java:54)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Target of Bean was never resolved: org.springframework.security.core.userdetails.UserDetailsService
        at org.pentaho.platform.engine.core.system.objfac.spring.BeanBuilder$1.invoke(BeanBuilder.java:159)
        at com.sun.proxy.$Proxy84.loadUserByUsername(Unknown Source)
        at org.pentaho.platform.plugin.services.security.userrole.ChainedUserDetailsService.loadUserByUsername(ChainedUserDetailsService.java:50)
        at org.pentaho.platform.plugin.services.security.userrole.PentahoCachingUserDetailsService.loadUserByUsername(PentahoCachingUserDetailsService.java:77)
        at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:114)
        ... 50 more
`
I attach the file catalina.log in a TXT
[catalina.txt](https://github.com/pentaho/pentaho-platform/files/2589035/catalina.txt)

Thanks!!

**Comment by dmcwhinnie** [comment]
Were you able to solve this? I am getting the same error, and can't figure out where my problem/typo is in the XML files.

**Comment by hieplq** [comment]
i get same with 8.0.2
resolve by build by myself with tag 8.2.0.2-466
https://github.com/zhicwu/docker-biserver-ce/issues/44#issuecomment-456352365

**Comment by deekal02** [comment]
@dmcwhinnie Which XML file are you referring here? I am facing the same issue..

**Comment by dmcwhinnie** [comment]
> @dmcwhinnie Which XML file are you referring here? I am facing the same issue..

I don't remember exactly, but it would be in one the files referenced here

[https://help.pentaho.com/Documentation/8.1/Setup/Installation/Archive/PostgreSQL_Repository](https://help.pentaho.com/Documentation/8.1/Setup/Installation/Archive/PostgreSQL_Repository)

**Comment by fravdd81** [comment]
Same issue seems to happen on 9.x versions.
By installing SNAPSHOT version, error doesn't occur and login is ok.
Tried finding differences between repo config file between versions, but I didn't find anything.
